In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.full(10, 1.2)

array([1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2])

In [7]:
a = np.array([1,3,5,7,9])
a

array([1, 3, 5, 7, 9])

In [8]:
a[2] = 10
a

array([ 1,  3, 10,  7,  9])

In [9]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0,1000, 11)

array([   0.,  100.,  200.,  300.,  400.,  500.,  600.,  700.,  800.,
        900., 1000.])

In [11]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [17]:
n[1][2]

np.int64(5)

In [19]:
n[1]

array([4, 5, 5])

In [20]:
n[:, 0]

array([1, 4, 7])

In [33]:
np.random.randn(5,2)

array([[ 1.00036589, -0.38109252],
       [-0.37566942, -0.07447076],
       [ 0.43349633,  1.27837923],
       [-0.63467931,  0.50839624],
       [ 0.21611601, -1.85861239]])

In [36]:
np.random.randint(low=0, high=100, size=(6,2))

array([[21, 43],
       [93, 80],
       [40, 70],
       [74, 37],
       [59, 17],
       [15, 30]])

In [66]:
a = np.arange(5)
a = a + 1
a
b = np.random.randint(low=1, high=5, size=(5))
b, a

(array([1, 1, 4, 4, 3]), array([1, 2, 3, 4, 5]))

In [67]:
a[a > b]

array([2, 5])

In [69]:
np.linspace(10, 100, 10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [70]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [71]:
df = np.zeros(10)

In [72]:
df.dtype

dtype('float64')

In [75]:
np.random.randint(low=0, high=6, size=(10))

array([4, 3, 1, 3, 0, 0, 5, 3, 2, 2])

In [78]:
np.random.randn(10) + 5

array([6.07966501, 5.85415383, 5.81947796, 6.16614883, 4.12636325,
       4.72539173, 4.76532285, 5.78394303, 3.88159931, 5.73512986])

In [79]:
np.random.rand(10)

array([0.15356567, 0.94669413, 0.29374373, 0.73660054, 0.47553897,
       0.16486714, 0.82745335, 0.5396978 , 0.35417242, 0.84199769])