In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.full(10, 1.2)

array([1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2])

In [7]:
a = np.array([1,3,5,7,9])
a

array([1, 3, 5, 7, 9])

In [8]:
a[2] = 10
a

array([ 1,  3, 10,  7,  9])

In [9]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0,1000, 11)

array([   0.,  100.,  200.,  300.,  400.,  500.,  600.,  700.,  800.,
        900., 1000.])

In [11]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [13]:
n[1][2]

np.int64(6)

In [14]:
n[1]

array([4, 5, 6])

In [15]:
n[:, 0]

array([1, 4, 7])

In [16]:
np.random.randn(5,2)

array([[ 0.77397883, -1.50450231],
       [-0.38394405,  0.35345161],
       [ 0.32073382, -1.47650919],
       [ 0.65308767,  0.87648569],
       [ 0.47758462, -0.08287741]])

In [17]:
np.random.randint(low=0, high=100, size=(6,2))

array([[84, 21],
       [95, 33],
       [19, 25],
       [32, 72],
       [70, 91],
       [27, 18]])

In [18]:
a = np.arange(5)
a = a + 1
a
b = np.random.randint(low=1, high=5, size=(5))
b, a

(array([1, 3, 1, 3, 1]), array([1, 2, 3, 4, 5]))

In [19]:
a[a > b]

array([3, 4, 5])

In [20]:
np.linspace(10, 100, 10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
df = np.zeros(10)

In [23]:
df.dtype

dtype('float64')

In [24]:
np.random.randint(low=0, high=6, size=(10))

array([1, 2, 2, 5, 1, 3, 1, 5, 5, 0])

In [25]:
np.random.randn(10) + 5

array([6.36852842, 5.21222931, 3.93719688, 4.39884126, 5.49973307,
       3.87280966, 4.63419594, 6.63598851, 7.39852808, 7.55144849])

In [26]:
np.random.rand(10)

array([0.85683859, 0.26857842, 0.85549132, 0.02163699, 0.73725976,
       0.86304477, 0.22776539, 0.59493349, 0.62747186, 0.0414199 ])

In [32]:
u = np.array([2, 3, 4, 5])

In [33]:
v = np.array([1, 0, 0, 2])

In [46]:
def vector_vector_mult(u, v):
    assert u.shape[0] == v.shape[0]

    running_total = 0
    n = u.shape[0]
    i = 0
    for i in range(n):
        running_total += (u[i] * v[i])
    return running_total

print(vector_vector_mult(u, v))

12


In [56]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])
v = np.array([1, 0.5, 2, 1])

v.shape[0]

4

In [58]:
def matrix_vector_mult(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = U[i].dot(v)
    return result
print(matrix_vector_mult(U, v))

[20.   6.   8.5]


In [59]:
U.dot(v)

array([20. ,  6. ,  8.5])

In [60]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0]
])

In [65]:
def matrix_matrix_mult(U, V):
    assert U.shape[1] == V.shape[0]
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    res = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        res[:, i] = U.dot(V[:, i])
    return res
print(matrix_matrix_mult(U, V))

[[14.  20.  13. ]
 [ 5.   6.   5. ]
 [ 5.   8.5  9. ]]


In [66]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])